<?php
// app/services/generators/BillboardGenerator.php — generate BillboardGui di atas kepala player
// Input: nodes hasil convert + nama player / role / level
// Output: Lua script siap paste

class BillboardGenerator {

    /**
     * Generate script BillboardGui overhead
     *
     * @param array $config {
     *   name: string,
     *   role: string,
     *   level: int,
     *   offsetY: float (default 3.5),
     *   size: [w, h] (default [200, 60]),
     *   maxDistance: int (default 100),
     *   theme: 'gold' | 'blue' | 'purple'
     * }
     */
    public static function generate($config = []) {
        $name        = $config['name']        ?? 'Player';
        $role        = $config['role']        ?? 'Member';
        $level       = (int)($config['level'] ?? 1);
        $offsetY     = (float)($config['offsetY'] ?? 3.5);
        $width       = (int)($config['size'][0] ?? 220);
        $height      = (int)($config['size'][1] ?? 70);
        $maxDistance = (int)($config['maxDistance'] ?? 120);
        $theme       = $config['theme']       ?? 'gold';

        // Palet warna per tema
        $themes = [
            'gold' => [
                'accent'    => 'Color3.fromRGB(212, 175, 55)',
                'accentHex' => '#d4af37',
                'nameColor' => 'Color3.fromRGB(244, 208, 63)',
                'roleColor' => 'Color3.fromRGB(192, 192, 200)',
                'levelColor'=> 'Color3.fromRGB(34, 197, 94)',
                'bgColor'   => 'Color3.fromRGB(15, 15, 20)',
            ],
            'blue' => [
                'accent'    => 'Color3.fromRGB(59, 130, 246)',
                'accentHex' => '#3b82f6',
                'nameColor' => 'Color3.fromRGB(147, 197, 253)',
                'roleColor' => 'Color3.fromRGB(192, 192, 200)',
                'levelColor'=> 'Color3.fromRGB(34, 197, 94)',
                'bgColor'   => 'Color3.fromRGB(15, 20, 35)',
            ],
            'purple' => [
                'accent'    => 'Color3.fromRGB(168, 85, 247)',
                'accentHex' => '#a855f7',
                'nameColor' => 'Color3.fromRGB(216, 180, 254)',
                'roleColor' => 'Color3.fromRGB(192, 192, 200)',
                'levelColor'=> 'Color3.fromRGB(34, 197, 94)',
                'bgColor'   => 'Color3.fromRGB(25, 15, 35)',
            ],
        ];
        $t = $themes[$theme] ?? $themes['gold'];

        $L = [];
        $L[] = '-- ============================================================';
        $L[] = '--  BILLBOARD OVERHEAD NAMETAG';
        $L[] = '--  Auto-generated by ARRR Studio';
        $L[] = '--  Nempel di atas kepala player, hadap ke kamera otomatis';
        $L[] = '-- ============================================================';
        $L[] = '';
        $L[] = 'local Players           = game:GetService("Players")';
        $L[] = 'local RunService        = game:GetService("RunService")';
        $L[] = 'local TweenService      = game:GetService("TweenService")';
        $L[] = '';
        $L[] = '-- ============================================================';
        $L[] = '--  FUNGSI: bikin BillboardGui untuk 1 karakter';
        $L[] = '-- ============================================================';
        $L[] = 'local function createNametag(character, playerName, roleText, levelNum)';
        $L[] = '    local head = character:WaitForChild("Head", 10)';
        $L[] = '    if not head then return end';
        $L[] = '';
        $L[] = '    -- Hapus billboard lama kalau ada';
        $L[] = '    local old = head:FindFirstChild("ARRR_Nametag")';
        $L[] = '    if old then old:Destroy() end';
        $L[] = '';
        $L[] = '    -- BillboardGui utama';
        $L[] = '    local billboard = Instance.new("BillboardGui")';
        $L[] = '    billboard.Name = "ARRR_Nametag"';
        $L[] = "    billboard.Size = UDim2.new(0, {$width}, 0, {$height})";
        $L[] = "    billboard.StudsOffsetWorldSpace = Vector3.new(0, {$offsetY}, 0)";
        $L[] = '    billboard.AlwaysOnTop = true';
        $L[] = "    billboard.MaxDistance = {$maxDistance}";
        $L[] = '    billboard.LightInfluence = 0';
        $L[] = '    billboard.ClipsDescendants = false';
        $L[] = '    billboard.Parent = head';
        $L[] = '';
        $L[] = '    -- Background container (Frame utama)';
        $L[] = '    local container = Instance.new("Frame")';
        $L[] = '    container.Name = "Container"';
        $L[] = '    container.Size = UDim2.fromScale(1, 1)';
        $L[] = '    container.BackgroundTransparency = 1';
        $L[] = '    container.Parent = billboard';
        $L[] = '';
        $L[] = '    -- ========================================================';
        $L[] = '    --  BADGE ICONS ROW (top)';
        $L[] = '    -- ========================================================';
        $L[] = '    local iconRow = Instance.new("Frame")';
        $L[] = '    iconRow.Name = "IconRow"';
        $L[] = '    iconRow.Size = UDim2.new(0, 100, 0, 24)';
        $L[] = '    iconRow.Position = UDim2.new(0.5, -50, 0, 0)';
        $L[] = '    iconRow.BackgroundTransparency = 1';
        $L[] = '    iconRow.Parent = container';
        $L[] = '';
        $L[] = '    local iconLayout = Instance.new("UIListLayout")';
        $L[] = '    iconLayout.FillDirection = Enum.FillDirection.Horizontal';
        $L[] = '    iconLayout.HorizontalAlignment = Enum.HorizontalAlignment.Center';
        $L[] = '    iconLayout.SortOrder = Enum.SortOrder.LayoutOrder';
        $L[] = '    iconLayout.Padding = UDim.new(0, 4)';
        $L[] = '    iconLayout.Parent = iconRow';
        $L[] = '';
        $L[] = '    -- Badge icons';
        $L[] = '    local badgeIcons = {"🎤", "💬", "👑"}';
        $L[] = '    local badgeColors = {';
        $L[] = '        Color3.fromRGB(30, 30, 40),';
        $L[] = '        Color3.fromRGB(30, 50, 90),';
        $L[] = '        Color3.fromRGB(90, 30, 60),';
        $L[] = '    }';
        $L[] = '    for i, icon in ipairs(badgeIcons) do';
        $L[] = '        local badge = Instance.new("Frame")';
        $L[] = '        badge.Name = "Badge" .. i';
        $L[] = '        badge.Size = UDim2.new(0, 22, 0, 22)';
        $L[] = '        badge.BackgroundColor3 = badgeColors[i]';
        $L[] = '        badge.BackgroundTransparency = 0.2';
        $L[] = '        badge.BorderSizePixel = 0';
        $L[] = '        badge.LayoutOrder = i';
        $L[] = '        badge.Parent = iconRow';
        $L[] = '';
        $L[] = '        local badgeCorner = Instance.new("UICorner")';
        $L[] = '        badgeCorner.CornerRadius = UDim.new(0, 6)';
        $L[] = '        badgeCorner.Parent = badge';
        $L[] = '';
        $L[] = '        local badgeStroke = Instance.new("UIStroke")';
        $L[] = '        badgeStroke.Color = Color3.fromRGB(200, 200, 210)';
        $L[] = '        badgeStroke.Thickness = 1';
        $L[] = '        badgeStroke.Transparency = 0.5';
        $L[] = '        badgeStroke.Parent = badge';
        $L[] = '';
        $L[] = '        local badgeText = Instance.new("TextLabel")';
        $L[] = '        badgeText.Size = UDim2.fromScale(1, 1)';
        $L[] = '        badgeText.BackgroundTransparency = 1';
        $L[] = '        badgeText.Text = icon';
        $L[] = '        badgeText.TextSize = 13';
        $L[] = '        badgeText.Font = Enum.Font.GothamBold';
        $L[] = '        badgeText.TextColor3 = Color3.fromRGB(255, 255, 255)';
        $L[] = '        badgeText.Parent = badge';
        $L[] = '    end';
        $L[] = '';
        $L[] = '    -- ========================================================';
        $L[] = '    --  NAME';
        $L[] = '    -- ========================================================';
        $L[] = '    local nameLabel = Instance.new("TextLabel")';
        $L[] = '    nameLabel.Name = "PlayerName"';
        $L[] = '    nameLabel.Size = UDim2.new(1, 0, 0, 20)';
        $L[] = '    nameLabel.Position = UDim2.new(0, 0, 0, 26)';
        $L[] = '    nameLabel.BackgroundTransparency = 1';
        $L[] = '    nameLabel.Text = playerName';
        $L[] = '    nameLabel.TextSize = 16';
        $L[] = '    nameLabel.Font = Enum.Font.GothamBold';
        $L[] = "    nameLabel.TextColor3 = {$t['nameColor']}";
        $L[] = '    nameLabel.TextStrokeTransparency = 0.3';
        $L[] = '    nameLabel.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)';
        $L[] = '    nameLabel.Parent = container';
        $L[] = '';
        $L[] = '    -- ========================================================';
        $L[] = '    --  ROLE';
        $L[] = '    -- ========================================================';
        $L[] = '    local roleLabel = Instance.new("TextLabel")';
        $L[] = '    roleLabel.Name = "Role"';
        $L[] = '    roleLabel.Size = UDim2.new(1, 0, 0, 16)';
        $L[] = '    roleLabel.Position = UDim2.new(0, 0, 0, 44)';
        $L[] = '    roleLabel.BackgroundTransparency = 1';
        $L[] = '    roleLabel.Text = roleText';
        $L[] = '    roleLabel.TextSize = 12';
        $L[] = '    roleLabel.Font = Enum.Font.Gotham';
        $L[] = "    roleLabel.TextColor3 = {$t['roleColor']}";
        $L[] = '    roleLabel.TextStrokeTransparency = 0.5';
        $L[] = '    roleLabel.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)';
        $L[] = '    roleLabel.Parent = container';
        $L[] = '';
        $L[] = '    -- ========================================================';
        $L[] = '    --  LEVEL (opsional, di bawah role)';
        $L[] = '    -- ========================================================';
        $L[] = '    local levelLabel = Instance.new("TextLabel")';
        $L[] = '    levelLabel.Name = "Level"';
        $L[] = '    levelLabel.Size = UDim2.new(1, 0, 0, 14)';
        $L[] = '    levelLabel.Position = UDim2.new(0, 0, 0, 58)';
        $L[] = '    levelLabel.BackgroundTransparency = 1';
        $L[] = '    levelLabel.Text = "Level " .. tostring(levelNum)';
        $L[] = '    levelLabel.TextSize = 11';
        $L[] = '    levelLabel.Font = Enum.Font.GothamBold';
        $L[] = "    levelLabel.TextColor3 = {$t['levelColor']}";
        $L[] = '    levelLabel.TextStrokeTransparency = 0.5';
        $L[] = '    levelLabel.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)';
        $L[] = '    levelLabel.Parent = container';
        $L[] = '';
        $L[] = '    return billboard';
        $L[] = 'end';
        $L[] = '';
        $L[] = '-- ============================================================';
        $L[] = '--  APPLY KE SEMUA PLAYER';
        $L[] = '-- ============================================================';
        $L[] = 'local function setupPlayer(player)';
        $L[] = '    local function onCharacter(character)';
        $L[] = '        -- Ambil data dari leaderstats kalau ada';
        $L[] = '        local roleText = "' . addslashes($role) . '"';
        $L[] = '        local levelNum = ' . $level . ';';
        $L[] = '';
        $L[] = '        local leaderstats = player:FindFirstChild("leaderstats")';
        $L[] = '        if leaderstats then';
        $L[] = '            local lv = leaderstats:FindFirstChild("Level")';
        $L[] = '            if lv and typeof(lv.Value) == "number" then';
        $L[] = '                levelNum = lv.Value';
        $L[] = '            end';
        $L[] = '        end';
        $L[] = '';
        $L[] = '        createNametag(character, player.Name, roleText, levelNum)';
        $L[] = '    end';
        $L[] = '';
        $L[] = '    if player.Character then onCharacter(player.Character) end';
        $L[] = '    player.CharacterAdded:Connect(onCharacter)';
        $L[] = 'end';
        $L[] = '';
        $L[] = '-- Setup player yang udah ada';
        $L[] = 'for _, player in ipairs(Players:GetPlayers()) do';
        $L[] = '    if player ~= Players.LocalPlayer then';
        $L[] = '        setupPlayer(player)';
        $L[] = '    end';
        $L[] = 'end';
        $L[] = '';
        $L[] = '-- Setup player yang baru join';
        $L[] = 'Players.PlayerAdded:Connect(function(player)';
        $L[] = '    if player ~= Players.LocalPlayer then';
        $L[] = '        setupPlayer(player)';
        $L[] = '    end';
        $L[] = 'end)';
        $L[] = '';
        $L[] = '-- Handle local player juga (opsional, hapus kalau nggak mau lihat sendiri)';
        $L[] = '-- setupPlayer(Players.LocalPlayer)';
        $L[] = '';
        $L[] = 'print("[ARRR] Billboard nametag aktif untuk", #Players:GetPlayers(), "player(s)")';

        return implode("\n", $L);
    }
}