<?php
// app/services/generators/LuaGenerator.php — behavior script, tree & report
class LuaGenerator {

    public static function generateBehaviorScript($nodes, array $ui = []) {
        $ui += ['name' => 'Canvas', 'gui' => 'GeneratedUI', 'singleRoot' => false];
        $L = [];
        $L[] = '-- ============================================================';
        $L[] = '--  BEHAVIOR SCRIPT (RunContext = Client, Parent = ScreenGui)';
        $L[] = '--  Generated by ArrStudioWeb v4';
        $L[] = '-- ============================================================';
        $L[] = '';
        $L[] = 'local TweenService = game:GetService("TweenService")';
        $L[] = 'local screenGui = script.Parent';
        $L[] = 'if not screenGui then';
        $L[] = '    warn("[ArrStudio] script.Parent is nil — pastikan script di dalam ScreenGui")';
        $L[] = '    return';
        $L[] = 'end';
        $L[] = '';
        $L[] = 'local canvas = screenGui:WaitForChild(' . LuaHelper::q($ui['name']) . ', 10)';
        $L[] = 'if not canvas then';
        $L[] = '    warn("[ArrStudio] ' . $ui['name'] . ' tidak ditemukan di ScreenGui")';
        $L[] = '    return';
        $L[] = 'end';
        $L[] = '';
        $L[] = '-- Helper: cari descendant berdasarkan nama (normalized)';
        $L[] = 'local function findByNormName(root, targetName)';
        $L[] = '    if not root or not targetName then return nil end';
        $L[] = '    local targetNorm = tostring(targetName):lower():gsub("[^%a%d]", "")';
        $L[] = '    for _, g in ipairs(root:GetDescendants()) do';
        $L[] = '        if g:IsA("GuiObject") then';
        $L[] = '            local n = g.Name:lower():gsub("[^%a%d]", "")';
        $L[] = '            if n == targetNorm then return g end';
        $L[] = '        end';
        $L[] = '    end';
        $L[] = '    return nil';
        $L[] = 'end';
        $L[] = '';
        $L[] = '-- Helper: safe FindFirstChild dengan retry';
        $L[] = 'local function safeFind(root, name)';
        $L[] = '    if not root then return nil end';
        $L[] = '    local found = root:FindFirstChild(name)';
        $L[] = '    if found then return found end';
        $L[] = '    -- Fallback: cari by normalized name';
        $L[] = '    local targetNorm = tostring(name):lower():gsub("[^%a%d]", "")';
        $L[] = '    for _, g in ipairs(root:GetDescendants()) do';
        $L[] = '        if g:IsA("GuiObject") then';
        $L[] = '            local n = g.Name:lower():gsub("[^%a%d]", "")';
        $L[] = '            if n == targetNorm then return g end';
        $L[] = '        end';
        $L[] = '    end';
        $L[] = '    return nil';
        $L[] = 'end';
        $L[] = '';

        ['pairs' => $pairs, 'buttons' => $buttons, 'usedBtn' => $usedBtn] = self::detectPairs($nodes);

        $idToNode = [];
        foreach ($nodes as $n) $idToNode[$n['id']] = $n;

        // FIX: Path generation pakai safeFind chain, bukan WaitForChild berantai
        // Biar nggak error kalau node belum ke-load
        $pathOf = function($n) use ($idToNode, $ui) {
            $parts = [$n['name']];
            $cur = $n;
            while (!empty($cur['parentId'])) {
                $cur = $idToNode[$cur['parentId']] ?? null;
                if (!$cur) break;
                array_unshift($parts, $cur['name']);
            }
            // Root = canvas itu sendiri (mode singleRoot)
            if ($ui['singleRoot']) array_shift($parts);
            if (!$parts) return 'canvas';

            // Bangun chain: safeFind(safeFind(safeFind(canvas, "A"), "B"), "C")
            $path = 'canvas';
            foreach ($parts as $p) {
                $path = 'safeFind(' . $path . ', ' . LuaHelper::q($p) . ')';
            }
            return $path;
        };

        $refs = [];
        foreach ($pairs as $pair) {
            $refs[$pair['btn']['id']] = $pair['btn'];
            $refs[$pair['panel']['id']] = $pair['panel'];
        }
        foreach ($buttons as $b) {
            if (!isset($usedBtn[$b['id']])) $refs[$b['id']] = $b;
        }
        ksort($refs);

        $varMap = [];
        $L[] = '-- Node references';
        foreach ($refs as $n) {
            $isBtn = in_array($n['robloxClass'], ['TextButton','ImageButton']);
            $varName = ($isBtn ? 'btn_' : 'obj_') . preg_replace('/[^A-Za-z0-9_]/', '', $n['name']);
            // Pastikan nama unik
            $varName = $varName . '_' . $n['id'];
            $varMap[$n['id']] = $varName;
            $L[] = "local {$varName} = " . $pathOf($n);
        }
        $L[] = '';

        $pairByBtn = [];
        foreach ($pairs as $pair) {
            $bid = $pair['btn']['id'];
            if (!isset($pairByBtn[$bid])) $pairByBtn[$bid] = ['btn' => $pair['btn'], 'panels' => []];
            $pairByBtn[$bid]['panels'][] = $pair['panel'];
        }

        if (!empty($pairByBtn)) {
            $L[] = '-- ============================================================';
            $L[] = '-- TOGGLE PAIRS';
            $L[] = '-- ============================================================';
            foreach ($pairByBtn as $group) {
                $btn = $group['btn'];
                $btnVar = $varMap[$btn['id']];
                $isOpenVar = 'isOpen_' . preg_replace('/[^A-Za-z0-9_]/', '', $btn['name']) . '_' . $btn['id'];

                $L[] = "-- {$btn['name']} toggles " . count($group['panels']) . ' panel(s)';
                $L[] = "if {$btnVar} then";
                $L[] = "    local {$isOpenVar} = false";
                $L[] = '';

                foreach ($group['panels'] as $panel) {
                    $pv = $varMap[$panel['id']];
                    $dur = $panel['transition']['duration'] ?? 0.35;
                    $ease = LuaHelper::mapEasing($panel['transition']['easing'] ?? 'ease-out');
                    $openX = (int)$panel['x'];
                    $openY = (int)$panel['y'];
                    $closedX = $openX + 30;
                    $bgTarget = NodeStyle::resolve($panel)['bgTransparency'];
                    $tweenVar = 'tweenInfo_' . preg_replace('/[^A-Za-z0-9_]/', '', $panel['name']) . '_' . $panel['id'];

                    $L[] = "    local {$tweenVar} = TweenInfo.new({$dur}, {$ease})";
                    $L[] = "    local {$pv}_openPos   = UDim2.new(0, {$openX}, 0, {$openY})";
                    $L[] = "    local {$pv}_closedPos = UDim2.new(0, {$closedX}, 0, {$openY})";
                    $L[] = "    if {$pv} then";
                    $L[] = "        {$pv}.Position = {$pv}_closedPos";
                    $L[] = "        {$pv}.Visible = false";
                    $L[] = "    end";
                    $L[] = '';
                }

                $L[] = "    {$btnVar}.MouseButton1Click:Connect(function()";
                $L[] = "        {$isOpenVar} = not {$isOpenVar}";

                foreach ($group['panels'] as $panel) {
                    $pv = $varMap[$panel['id']];
                    $bgTarget = NodeStyle::resolve($panel)['bgTransparency'];
                    $tweenVar = 'tweenInfo_' . preg_replace('/[^A-Za-z0-9_]/', '', $panel['name']) . '_' . $panel['id'];

                    $L[] = "        if {$pv} then";
                    $L[] = "            if {$isOpenVar} then";
                    $L[] = "                {$pv}.Visible = true";
                    $L[] = "                TweenService:Create({$pv}, {$tweenVar}, {Position = {$pv}_openPos, BackgroundTransparency = {$bgTarget}}):Play()";
                    $L[] = "            else";
                    $L[] = "                local t = TweenService:Create({$pv}, {$tweenVar}, {Position = {$pv}_closedPos, BackgroundTransparency = 1})";
                    $L[] = "                t:Play()";
                    $L[] = "                t.Completed:Wait()";
                    $L[] = "                {$pv}.Visible = false";
                    $L[] = "            end";
                    $L[] = "        end";
                }
                $L[] = "    end)";
                $L[] = "end";
                $L[] = '';
            }
        }

        $hoverables = array_filter($nodes, fn($n) => !empty($n['transition']) && ($n['robloxClass'] === 'TextButton' || !empty($n['isButtonLike'])));
        if (!empty($hoverables)) {
            $L[] = '-- ============================================================';
            $L[] = '-- HOVER EFFECTS';
            $L[] = '-- ============================================================';
            foreach ($hoverables as $n) {
                if (!isset($varMap[$n['id']])) continue;
                $v = $varMap[$n['id']];
                $dur = $n['transition']['duration'];
                $ease = LuaHelper::mapEasing($n['transition']['easing']);
                $vname = preg_replace('/[^A-Za-z0-9_]/', '', $n['name']) . '_' . $n['id'];
                $baseX = (int)$n['x'];
                $baseY = (int)$n['y'];
                $L[] = "-- hover: {$n['name']}";
                $L[] = "if {$v} then";
                $L[] = "    local hoverIn_{$vname}  = TweenInfo.new({$dur}, {$ease})";
                $L[] = "    local hoverOut_{$vname} = TweenInfo.new({$dur}, {$ease})";
                $L[] = "    {$v}.MouseEnter:Connect(function()";
                $L[] = "        TweenService:Create({$v}, hoverIn_{$vname}, {Position = UDim2.new(0, " . ($baseX - 3) . ", 0, {$baseY})}):Play()";
                $L[] = "    end)";
                $L[] = "    {$v}.MouseLeave:Connect(function()";
                $L[] = "        TweenService:Create({$v}, hoverOut_{$vname}, {Position = UDim2.new(0, {$baseX}, 0, {$baseY})}):Play()";
                $L[] = "    end)";
                $L[] = "end";
                $L[] = '';
            }
        }

        $remaining = array_filter($buttons, fn($b) => !isset($usedBtn[$b['id']]));
        if (!empty($remaining)) {
            $L[] = '-- ============================================================';
            $L[] = '-- INTERACTIVE BUTTONS';
            $L[] = '-- ============================================================';
            $L[] = '';

            foreach ($remaining as $n) {
                $v = $varMap[$n['id']] ?? null;
                if (!$v) continue;

                $action = $n['action'] ?? '';
                $target = $n['target'] ?? '';
                $L[] = "if {$v} then";

                if ($action === 'toggle' && $target !== '') {
                    $L[] = "    -- Toggle fallback: {$n['name']} -> {$target}";
                    $L[] = "    {$v}.MouseButton1Click:Connect(function()";
                    $L[] = "        local tgt = findByNormName(canvas, '{$target}')";
                    $L[] = "        if tgt then tgt.Visible = not tgt.Visible end";
                    $L[] = "    end)";

                } elseif ($action === 'close' && $target !== '') {
                    $L[] = "    -- Close: {$n['name']} -> {$target}";
                    $L[] = "    {$v}.MouseButton1Click:Connect(function()";
                    $L[] = "        local tgt = findByNormName(canvas, '{$target}')";
                    $L[] = "        if tgt then tgt.Visible = false end";
                    $L[] = "    end)";

                } elseif ($action === 'switch' && !empty($n['isToggleSwitch'])) {
                    $isOn = !empty($n['isOn']);
                    $L[] = "    -- Toggle Switch: {$n['name']}";
                    $L[] = "    local {$v}_on = " . ($isOn ? 'true' : 'false');
                    $L[] = "    {$v}.MouseButton1Click:Connect(function()";
                    $L[] = "        {$v}_on = not {$v}_on";
                    $L[] = "        if {$v}_on then";
                    $L[] = "            TweenService:Create({$v}, TweenInfo.new(0.2), {BackgroundColor3 = Color3.fromRGB(124,58,237)}):Play()";
                    $L[] = "        else";
                    $L[] = "            TweenService:Create({$v}, TweenInfo.new(0.2), {BackgroundColor3 = Color3.fromRGB(48,49,58)}):Play()";
                    $L[] = "        end";
                    $L[] = "    end)";

                } elseif ($action === 'tab' && $target !== '') {
                    $L[] = "    -- Tab: {$n['name']} -> {$target}";
                    $L[] = "    {$v}.MouseButton1Click:Connect(function()";
                    $L[] = "        for _, g in ipairs(canvas:GetDescendants()) do";
                    $L[] = "            if g:IsA('GuiObject') and g.Name:match('^Content') then";
                    $L[] = "                g.Visible = false";
                    $L[] = "            end";
                    $L[] = "        end";
                    $L[] = "        local tgt = findByNormName(canvas, '{$target}')";
                    $L[] = "        if tgt then tgt.Visible = true end";
                    $L[] = "    end)";

                } elseif ($action === 'select') {
                    $L[] = "    -- Select: {$n['name']}";
                    $L[] = "    {$v}.MouseButton1Click:Connect(function()";
                    $L[] = "        print('selected: {$n['name']}')";
                    $L[] = "    end)";

                } elseif ($action === 'play') {
                    $L[] = "    -- Play/Pause: {$n['name']}";
                    $L[] = "    local {$v}_playing = false";
                    $L[] = "    {$v}.MouseButton1Click:Connect(function()";
                    $L[] = "        {$v}_playing = not {$v}_playing";
                    $L[] = "        {$v}.Text = {$v}_playing and '⏸' or '▶'";
                    $L[] = "    end)";

                } else {
                    $L[] = "    -- Button: {$n['name']}";
                    $L[] = "    {$v}.MouseButton1Click:Connect(function()";
                    $L[] = "        print('clicked: {$n['name']}')";
                    $L[] = "    end)";
                }
                $L[] = "end";
                $L[] = '';
            }
        }

        $switches = array_filter($nodes, fn($n) => ($n['action'] ?? '') === 'switch' && !empty($n['isToggleSwitch']));
        if (!empty($switches)) {
            $L[] = '-- ============================================================';
            $L[] = '-- TOGGLE SWITCHES';
            $L[] = '-- ============================================================';
            foreach ($switches as $sw) {
                $sv = $varMap[$sw['id']] ?? null;
                if (!$sv) continue;
                $isOn = !empty($sw['isOn']);
                $L[] = "-- Switch: {$sw['name']}";
                $L[] = "if {$sv} then";
                $L[] = "    local {$sv}_on = " . ($isOn ? 'true' : 'false');
                $L[] = "    {$sv}.MouseButton1Click:Connect(function()";
                $L[] = "        {$sv}_on = not {$sv}_on";
                $L[] = "        if {$sv}_on then";
                $L[] = "            TweenService:Create({$sv}, TweenInfo.new(0.2), {BackgroundColor3 = Color3.fromRGB(124,58,237)}):Play()";
                $L[] = "        else";
                $L[] = "            TweenService:Create({$sv}, TweenInfo.new(0.2), {BackgroundColor3 = Color3.fromRGB(48,49,58)}):Play()";
                $L[] = "        end";
                $L[] = "    end)";
                $L[] = "end";
                $L[] = '';
            }
        }

        $backdropClose = array_filter($nodes, fn($n) => ($n['action'] ?? '') === 'close' && !empty($n['selfHidden']));
        if (!empty($backdropClose)) {
            $L[] = '-- ============================================================';
            $L[] = '-- BACKDROP CLOSE';
            $L[] = '-- ============================================================';
            foreach ($backdropClose as $bn) {
                $bv = $varMap[$bn['id']] ?? null;
                if (!$bv) continue;
                $tgt = $bn['target'] ?? '';
                if ($tgt === '') continue;
                $L[] = "-- Backdrop: {$bn['name']} -> {$tgt}";
                $L[] = "if {$bv} then";
                $L[] = "    {$bv}.MouseButton1Click:Connect(function()";
                $L[] = "        local tgt = findByNormName(canvas, '{$tgt}')";
                $L[] = "        if tgt then tgt.Visible = false end";
                $L[] = "    end)";
                $L[] = "end";
                $L[] = '';
            }
        }

        $L[] = '-- Guard: initial tab visibility';
        $L[] = 'for _, g in ipairs(canvas:GetDescendants()) do';
        $L[] = '    if g:IsA("GuiObject") and g.Name:match("^ContentLibrary$") then';
        $L[] = '        g.Visible = true';
        $L[] = '    end';
        $L[] = 'end';
        $L[] = '';
        $L[] = 'print("[ArrStudio] Behavior script loaded")';
        return implode("\n", $L);
    }

    public static function detectPairs($nodes) {
        $buttons = array_values(array_filter($nodes, fn($n) =>
            in_array($n['robloxClass'], ['TextButton','ImageButton']) &&
            empty($n['isToggleSwitch'])
        ));

        $hiddenPanels = array_values(array_filter($nodes, function($n) {
            if (empty($n['selfHidden'])) return false;
            if (!in_array($n['robloxClass'], ['Frame','ScrollingFrame'])) return false;
            if (($n['action'] ?? '') === 'close') return false;
            if (!empty($n['isToggleSwitch'])) return false;
            if ($n['w'] < 60 || $n['h'] < 60) return false;
            if (($n['action'] ?? '') === 'toggle' && empty($n['target'])) return false;
            return true;
        }));

        $pairs = [];
        $usedBtn = [];
        $usedPanel = [];

        $norm = fn($s) => strtolower(preg_replace('/[^a-z0-9]/i', '', (string)$s));

        foreach ($hiddenPanels as $panel) {
            if (isset($usedPanel[$panel['id']])) continue;

            $panelKeys = array_filter([
                $norm($panel['sourceId'] ?? ''),
                $norm($panel['id'] ?? ''),
                $norm($panel['name'] ?? ''),
            ]);
            $btn = null;

            foreach ($buttons as $b) {
                if (isset($usedBtn[$b['id']])) continue;
                if (($b['action'] ?? '') !== 'toggle') continue;
                $tgt = $norm($b['target'] ?? '');
                if ($tgt === '') continue;
                $sid = $norm($panel['sourceId'] ?? '');
                if ($sid !== '' && $sid === $tgt) {
                    $btn = $b; break;
                }
            }

            if (!$btn) {
                foreach ($buttons as $b) {
                    if (isset($usedBtn[$b['id']])) continue;
                    if (($b['action'] ?? '') !== 'toggle') continue;
                    $tgt = $norm($b['target'] ?? '');
                    if ($tgt === '') continue;
                    foreach ($panelKeys as $pk) {
                        if ($pk !== '' && (str_contains($pk, $tgt) || str_contains($tgt, $pk))) {
                            $btn = $b; break 2;
                        }
                    }
                }
            }

            if (!$btn) {
                $panelRoot = preg_replace('/Panel\d*$|Popup$|Menu$|Container$|Frame$|Backdrop$/i', '', $panel['name'] ?? '');
                foreach ($buttons as $b) {
                    if (isset($usedBtn[$b['id']])) continue;
                    if (($b['action'] ?? '') !== 'toggle') continue;
                    $btnRoot = preg_replace('/Button$|Toggle$|Btn$|Icon$/i', '', $b['name'] ?? '');
                    if ($btnRoot && $panelRoot && strtolower($btnRoot) === strtolower($panelRoot)) {
                        $btn = $b; break;
                    }
                }
            }

            if ($btn) {
                $usedBtn[$btn['id']] = true;
                $usedPanel[$panel['id']] = true;
                $pairs[] = ['btn' => $btn, 'panel' => $panel];
            }
        }
        return ['pairs' => $pairs, 'buttons' => $buttons, 'usedBtn' => $usedBtn];
    }

    public static function renderTreeText($nodes) {
        $lines = [];
        $lines[] = 'Folder "GeneratedUIPack"';
        $lines[] = '└─ ScreenGui "GeneratedUI"';
        $lines[] = '   ├─ Script "GeneratedUI_Behavior" (RunContext=Client)';
        $lines[] = '   └─ Frame "Canvas" (800x600, UIScale auto)';

        $byParent = [];
        foreach ($nodes as $n) {
            $key = $n['parentId'] ?: 'root';
            $byParent[$key][] = $n;
        }

        $walk = function($key, $prefix) use (&$walk, &$byParent, &$lines) {
            $children = $byParent[$key] ?? [];
            $cnt = count($children);
            foreach ($children as $i => $n) {
                $isLast = $i === $cnt - 1;
                $conn = $isLast ? '└─ ' : '├─ ';
                $txt = !empty($n['text']) ? ' "' . mb_substr($n['text'], 0, 28) . (mb_strlen($n['text']) > 28 ? '…' : '') . '"' : '';
                $tags = [];
                if ($n['selfHidden']) $tags[] = 'hidden';
                if (!empty($n['gradient'])) $tags[] = 'gradient';
                if (!empty($n['action'])) $tags[] = "action:{$n['action']}";
                if (!empty($n['unsupported'])) $tags[] = '⚠ ' . count($n['unsupported']);
                $tag = $tags ? ' [' . implode(', ', $tags) . ']' : '';
                $lines[] = "{$prefix}{$conn}{$n['robloxClass']} \"{$n['name']}\" ({$n['x']},{$n['y']} {$n['w']}x{$n['h']}){$txt}{$tag}";
                $walk($n['id'], $prefix . ($isLast ? '   ' : '│  '));
            }
        };
        $walk('root', '      ');
        $lines[] = '';
        $lines[] = 'Total: ' . count($nodes) . ' instances + 1 Script';
        return implode("\n", $lines);
    }

    public static function renderReport($nodes) {
        $lines = [];
        $total = 0;
        $affected = [];
        foreach ($nodes as $n) {
            if (!empty($n['unsupported'])) {
                $affected[] = $n;
                $total += count($n['unsupported']);
            }
        }
        $lines[] = '════════════════════════════════════════════';
        $lines[] = '  UNSUPPORTED FEATURE REPORT';
        $lines[] = '════════════════════════════════════════════';
        $lines[] = '';
        $lines[] = "Total issues: {$total}  |  Affected nodes: " . count($affected);
        $lines[] = '';
        if (!$affected) {
            $lines[] = '✓ Tidak ada fitur unsupported.';
            return implode("\n", $lines);
        }
        foreach ($affected as $n) {
            $lines[] = "▸ {$n['robloxClass']} \"{$n['name']}\"";
            foreach ($n['unsupported'] as $iss) {
                $lines[] = "    • {$iss['label']}: {$iss['value']}";
                $lines[] = "      → {$iss['reason']}";
            }
            $lines[] = '';
        }
        return implode("\n", $lines);
    }
}